# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFlW-xY5LKfgV4KxtCzVOvvf57ur6Ze_
"""

#!pip install streamlit
import sys
import streamlit as st
from PIL import Image
import PyPDF2
import openai
from dotenv import load_dotenv
import os

load_dotenv()  # Loads environment variables from .env
openai.api_key = os.getenv("OPENAI_API_KEY")


def extract_text_from_pdf(file):
    pdf_reader = PyPDF2.PdfReader(file)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text()
    st.write(text)
    return text

def generate_response(query, document_text):
    prompt = f"Answer the following question based on the document:\n\n{document_text}\n\nQuestion: {query}\nAnswer:"
    response = openai.completions.create(  # Use openai.completions.create instead
        model="gpt-3.5-turbo-instruct",  # 'engine' is now 'model'
        prompt=prompt,
        max_tokens=100
    )
    return response.choices[0].choices[0].text.strip()


def main():
    st.set_page_config(page_title="PDF Chatbot", page_icon="📄", layout="wide")

    # Sidebar
    with st.sidebar:
        st.image("https://cdn-icons-png.flaticon.com/512/337/337946.png", width=100)
        st.title("📄 PDF Chatbot")
        st.markdown("""
        **Features of this version:**
        - Upload PDFs 📤
        - Chat with your document 💬
        - AI-powered responses 🤖
        """)
        st.divider()
        

    # Main Content
    st.title("Chat with Your PDF 📄🤖")
    uploaded_file = st.file_uploader("Upload a PDF", type=["pdf"], accept_multiple_files=False)

    if uploaded_file is not None:
        st.success("PDF uploaded successfully!")
        st.info("Now you can start chatting with your document.")
        document_text = extract_text_from_pdf(uploaded_file)

    # Initialize session state for storing messages
    if "messages" not in st.session_state:
        st.session_state.messages = []

    user_input = st.text_input("Ask a question about the PDF:")

    if user_input:
        # Add the user's question to the session state
        st.session_state.messages.append({"role": "user", "content": user_input})

        # Generate a response using the PDF text
        response = generate_response(user_input, document_text)

        # Add the AI's response to the session state
        st.session_state.messages.append({"role": "assistant", "content": response})

    # Display the conversation
    for msg in st.session_state.messages:
        if msg["role"] == "user":
            st.write("**You:**", msg["content"])
        else:
            st.write("🤖 **Bot:**", msg["content"])

    # Input field LAST (appears at bottom)
    if user_input := st.chat_input("Ask a question about the PDF:"):
        # Add to history
        st.session_state.messages.append({"role": "user", "content": user_input})
        
        # Generate response
        response = generate_response(user_input, document_text)
        
        # Add bot response
        st.session_state.messages.append({"role": "assistant", "content": response})
        
        # Force refresh to show new messages
        st.rerun()

        

if __name__ == "__main__":
    main()
